server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    include /etc/nginx/mime.types;

    # Se pedir uma imagem/arquivo que existe, entrega o arquivo
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Força cache para imagens (opcional, melhora performance)
    location /assets/ {
        alias /usr/share/nginx/html/assets/;
        try_files $uri =404;
    }
}